<?php
namespace Core\Uti\Tools;

class SysConstant
{
    const FRAMEWORK_VERSION = 'FRAMEWORK_VERSION';
    const REQUIRE_PHP_VERSION = 'REQUIRE_PHP_VERSION';
    const REQUIRE_SWOOLE_VERSION = 'REQUIRE_SWOOLE_VERSION';
    const FRAMEWORK_LOG_PATH = 'FRAMEWORK_LOG_PATH';
}