<?php
namespace App\Components\Wechat\WechatMessageType;

class WechatVoice extends AbstractEvent
{
    protected $media_id;

    protected $format;

    protected $recognition;

    public function defaultResponse()
    {
        return 'your media id is '.$this->to_user_name;
    }

    public function setData($message)
    {
        parent::setData($message); // TODO: Change the autogenerated stub
        $this->media_id = $message['MediaId'];
        $this->format = $message['Format'];
        $this->recognition = isset($message['Recognition']) ? $message['Recognition'] : '';
    }
}