<?php
namespace App\Components\Wechat\WechatMessageType;

class WechatVideo extends AbstractEvent
{
    protected $media_id;

    protected $thumbMediaId;

    public function defaultResponse()
    {

    }

    public function setData($message)
    {
        parent::setData($message); // TODO: Change the autogenerated stub
        $this->media_id = $message['MediaId'];
        $this->thumbMediaId = $message['ThumbMediaId'];
    }
}