<?php
namespace App\Components\Wechat\WechatMessageType;

use Core\FrameEntry;

class WechatText extends AbstractEvent
{
    protected $content;

    public function defaultResponse()
    {
        var_dump($this->content);
        switch($this->content){
            case '我爱你':
                $res = '🐱🐱 也爱你';
                break;
            case '你是谁':
                $res = '你猜猜❓';
                break;
            case 'zmisgod':
                $res = "<a href='https://zmis.me'>zmis.me官网</a>";
                break;
            case '官网':
                $res = "<a href='https://zmis.me'>zmis.me官网</a>";
                break;
            case '你好':
                $res = '😄 你好呀！';
                break;
            case '你女朋友是谁':
                $res = ' 🐶 🥚 ';
                break;
            case '什么狗蛋':
                $res = '口天吴 🐶 🥚 呀:)';
                break;
            case '菜单':
                $res = <<<EPR
试试关键词：
我爱你
你是谁
zmisgod
官网
你好
你女朋友是谁
服务器状态
EPR;
                break;
            case '服务器状态':
                $frameEntry = new FrameEntry();
                $data = $frameEntry->getStatus();
                $res = $data['msg'];
                break;
            default:
                $res = '回复：菜单，查看更多内容';
                break;
        }
        return $res;
    }

    public function setData($message)
    {
        $this->content = $message['Content'];
        parent::setData($message); // TODO: Change the autogenerated stub
    }
}